version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - godot
    - gosec
    - gocritic
    - gocyclo
    - importas
    - maintidx
    - makezero
    - nilerr
    - nlreturn
    - nolintlint
    - nonamedreturns
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - usestdlibvars
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - cyclop
  settings:
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    tagliatelle:
      case:
        rules:
          json: snake

formatters:
  enable:
    - goimports
