linters:
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - decorder
    - dupl
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - goconst
    - godot
    - goimports
    - gosec
    - gocritic
    - gocyclo
    - gosec
    - importas
    - maintidx
    - makezero
    - nilerr
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - predeclared
    - revive
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - unconvert
    - usestdlibvars

linters-settings:
  cyclop:
    skip-tests: true
  tagliatelle:
    case:
      rules:
        json: snake