project_name: gremlins
before:
  hooks:
    - make clean
    - go mod download
builds:
  - main: ./cmd/gremlins
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
release:
  github:
  draft: true
  prerelease: auto
nfpms:
  - homepage: https://github.com/go-gremlins/gremlins
    description: A mutation testing tool for Go.
    license: Apache 2.0 License
    maintainer: Davide Petilli <davide.petilli@gmail.com>
    formats:
      - deb
      - rpm
brews:
  - tap:
      owner: go-gremlins
      name: homebrew-tap
      branch: main
      token: "{{ .Env.WORKFLOW_PAT }}"
    folder: Formula
    homepage: https://github.com/go-gremlins/gremlins
    description: A mutation testing tool for Go.
    license: Apache 2.0 License
    skip_upload: auto
    test: |
      system "#{bin}/gremlins --version"
checksum:
  name_template: 'checksums.txt'
source:
  enabled: true
changelog:
  skip: false
  sort: asc
  use: github-native
snapshot:
  name_template: "{{ .Tag }}-next"